### ISSUE TITLE
Error: Cannot find module 'xxxx/xxxx/node_modules/lzma-native/binding-v3.0.4-node-v64-darwin-x64/lzma_native.node'

### ISSUE THREAD

**Issue by lanjinglingxx** [addaleax/lzma-native#100]
Error: Cannot find module 'xxxx/xxxx/node_modules/lzma-native/binding-v3.0.4-node-v64-darwin-x64/lzma_native.node'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at /Users/li/Documents/doctor_system/branch/patient/MyFirstApp/node_modules/lzma-native/index.js:13:14
    at Object.<anonymous> (/Users/li/Documents/doctor_system/branch/patient/MyFirstApp/node_modules/lzma-native/index.js:595:3)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12) code: 'MODULE_NOT_FOUND' }

**Comment by lanjinglingxx** [comment]
node version 10.16.0

**Comment by addaleax** [comment]
This doesn’t contain enough information to debug this, but you may want to update to the latest version of `lzma-native` either way.

**Comment by lanjinglingxx** [comment]
Temporarily resolved the problem
