### ISSUE TITLE
Pre-built binaries not installable for lzma-native@6.0.1 and node@14.15.4

### ISSUE THREAD

**Issue by bemesquita** [addaleax/lzma-native#109]
```
npm install

> lzma-native@6.0.1 install C:\Users\cabemes\projects\de-mobile-electron\node_modules\lzma-native
> node-pre-gyp install --fallback-to-build && rimraf build

node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp WARN Pre-built binaries not installable for lzma-native@6.0.1 and node@14.15.4 (node-v83 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp WARN Hit error unable to get local issuer certificate
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: unable to get local issuer certificate
gyp ERR! stack     at TLSSocket.onConnectSecure (_tls_wrap.js:1497:34)
gyp ERR! stack     at TLSSocket.emit (events.js:315:20)
gyp ERR! stack     at TLSSocket._finishInit (_tls_wrap.js:932:8)
gyp ERR! stack     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:706:12)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\nodejs\\node.exe" "C:\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=C:\\Users\\cabemes\\projects\\de-mobile-electron\\node_modules\\lzma-native\\binding-v6.0.1-n-api-win32-x64\\lzma_native.node" "--module_name=lzma_native" "--module_path=C:\\Users\\cabemes\\projects\\de-mobile-electron\\node_modules\\lzma-native\\binding-v6.0.1-n-api-win32-x64" "--napi_version=7" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v83" "--python=python2.7" "--msvs_version=2015"
gyp ERR! cwd C:\Users\cabemes\projects\de-mobile-electron\node_modules\lzma-native
gyp ERR! node -v v14.15.4
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\nodejs\node.exe C:\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\Users\cabemes\projects\de-mobile-electron\node_modules\lzma-native\binding-v6.0.1-n-api-win32-x64\lzma_native.node --module_name=lzma_native --module_path=C:\Users\cabemes\projects\de-mobile-electron\node_modules\lzma-native\binding-v6.0.1-n-api-win32-x64 --napi_version=7 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83 --python=python2.7 --msvs_version=2015' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\cabemes\projects\de-mobile-electron\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1048:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
node-pre-gyp ERR! System Windows_NT 10.0.16299
node-pre-gyp ERR! command "C:\\nodejs\\node.exe" "C:\\Users\\cabemes\\projects\\de-mobile-electron\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\cabemes\projects\de-mobile-electron\node_modules\lzma-native
node-pre-gyp ERR! node -v v14.15.4
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! lzma-native@6.0.1 install: `node-pre-gyp install --fallback-to-build && rimraf build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the lzma-native@6.0.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\cabemes\AppData\Roaming\npm-cache\_logs\2021-03-31T01_40_50_308Z-debug.log
```

**Comment by addaleax** [comment]
@bemesquita The error here is:

> Hit error unable to get local issuer certificate

I assume that that’s an issue with a Proxy in your configuration?

**Comment by bemesquita** [comment]
I thought it was at first, but my machine is not under proxy and npm install works for other dependencies. Double checked my .npmrc file and looks ok.

**Comment by addaleax** [comment]
I’m not sure what to do then – it works for me locally, and I’m not really in any position to debug your TLS config. (Maybe it’s something Windows-specific?)

**Comment by bemesquita** [comment]
Yeah, I guess! I will keep investigating and post if I have any updates, you can close the issue if you want.

**Comment by addaleax** [comment]
lzma-native@8.x is identical to @7.x except that it uses prebuildify instead of node-pre-gyp, so a lot of these issues should have gone away now. Please let me know if anything doesn’t work as it should!
