### ISSUE TITLE
Startup error from inside GH Actions

### ISSUE THREAD

**Issue by nektro** [addaleax/lzma-native#121]
`Error: /lib/x86_64-linux-gnu/libc.so.6: version 'GLIBC_2.32' not found (required by /home/runner/work/actions-setup-zig/actions-setup-zig/dist/binding-v4.0.6-node-v93-linux-x64/lzma_native.node)`

Tried using this in a Github Action through [`decompress-tarxz`](https://www.npmjs.com/package/decompress-tarxz) and got the following error.

Full run: https://github.com/nektro/actions-setup-zig/runs/4501328005

```
Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /home/runner/work/actions-setup-zig/actions-setup-zig/dist/binding-v4.0.6-node-v93-linux-x64/lzma_native.node)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1025:18)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.5766 (/home/runner/work/actions-setup-zig/actions-setup-zig/webpack:/setup-zig/node_modules/lzma-native/binding-v4.0.6-node-v93-linux-x64/lzma_native.node:1:1)
    at __nccwpck_require__ (/home/runner/work/actions-setup-zig/actions-setup-zig/webpack:/setup-zig/webpack/bootstrap:21:1)
    at /home/runner/work/actions-setup-zig/actions-setup-zig/webpack:/setup-zig/node_modules/lzma-native/index.js:13:1
    at Object.4914 (/home/runner/work/actions-setup-zig/actions-setup-zig/dist/index.js:20387:3)
    at __nccwpck_require__ (/home/runner/work/actions-setup-zig/actions-setup-zig/webpack:/setup-zig/webpack/bootstrap:21:1)
```

**Comment by nektro** [comment]
Just realized their `lzma-native` version is very out of date, will report back

**Comment by nektro** [comment]
switched to `@felipecrs/decompress-tarxz` fork which has the updated version and worked.

sorry for the troubles.
