### ISSUE TITLE
'node-pre-gyp' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by patilbhupesh** [addaleax/lzma-native#142]
``` npm ERR! code 1
npm ERR! path D:\work-space\Mercury\apps\node_modules\lzma-native
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node-pre-gyp install --fallback-to-build && rimraf build
npm ERR! 'node-pre-gyp' is not recognized as an internal or external command,
npm ERR! operable program or batch file.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\a00572050\AppData\Local\npm-cache\_logs\2024-06-24T07_09_47_491Z-debug-0.log ```

**Comment by patilbhupesh** [comment]
this is issue occurred when i used `"electron-rebuild": "^2.3.2"` dependency 
 
 with node version `20.0.0` 
 
 
 ```
 npm ERR! code 1
npm ERR! path D:\work-space\Mercury\apps\node_modules\lzma-native
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node-pre-gyp install --fallback-to-build && rimraf build
npm ERR! Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\a00572050\AppData\Roaming\nvm\v20.0.0\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=D:\work-space\Mercury\apps\node_modules\lzma-native\binding-v6.0.1-n-api-win32-x64\lzma_native.node --module_name=lzma_native --module_path=D:\work-space\Mercury\apps\node_modules\lzma-native\binding-v6.0.1-n-api-win32-x64 --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v115' (1)
npm ERR! node-pre-gyp info it worked if it ends with ok
npm ERR! node-pre-gyp info using node-pre-gyp@0.11.0
npm ERR! node-pre-gyp info using node@20.0.0 | win32 | x64
npm ERR! node-pre-gyp WARN Using request for node-pre-gyp https download
npm ERR! node-pre-gyp info check checked for "D:\work-space\Mercury\apps\node_modules\lzma-native\binding-v6.0.1-n-api-win32-x64\lzma_native.node" (not found)
npm ERR! node-pre-gyp http GET https://node-pre-gyp.addaleax.net/lzma-native/lzma_native-v6.0.1-n-api-win32-x64.tar.gz
npm ERR! node-pre-gyp WARN Pre-built binaries not installable for lzma-native@6.0.1 and node@20.0.0 (node-v115 ABI, unknown) (falling back to source compile with node-gyp)
npm ERR! node-pre-gyp WARN Hit error unable to get local issuer certificate
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.3.1
npm ERR! gyp info using node@20.0.0 | win32 | x64
npm ERR! gyp info ok
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.3.1
npm ERR! gyp info using node@20.0.0 | win32 | x64
npm ERR! gyp info find Python using Python version 3.7.3 found at "C:\Users\a00572050\AppData\Local\Programs\Python\Python37\python.exe"
npm ERR! gyp http GET https://nodejs.org/download/release/v20.0.0/node-v20.0.0-headers.tar.gz
npm ERR! gyp WARN install got an error, rolling back install
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack FetchError: request to https://nodejs.org/download/release/v20.0.0/node-v20.0.0-headers.tar.gz failed, reason: unable to get local issuer certificate
npm ERR! gyp ERR! stack     at ClientRequest.<anonymous> (C:\Users\a00572050\AppData\Roaming\nvm\v20.0.0\node_modules\npm\node_modules\node-gyp\node_modules\minipass-fetch\lib\index.js:130:14)
npm ERR! gyp ERR! stack     at ClientRequest.emit (node:events:511:28)
npm ERR! gyp ERR! stack     at TLSSocket.socketErrorListener (node:_http_client:495:9)
npm ERR! gyp ERR! stack     at TLSSocket.emit (node:events:523:35)
npm ERR! gyp ERR! stack     at emitErrorNT (node:internal/streams/destroy:151:8)
npm ERR! gyp ERR! stack     at emitErrorCloseNT (node:internal/streams/destroy:116:3)
npm ERR! gyp ERR! stack     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
npm ERR! gyp ERR! System Windows_NT 10.0.22621
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\a00572050\\AppData\\Roaming\\nvm\\v20.0.0\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=D:\\work-space\\Mercury\\apps\\node_modules\\lzma-native\\binding-v6.0.1-n-api-win32-x64\\lzma_native.node" "--module_name=lzma_native" "--module_path=D:\\work-space\\Mercury\\apps\\node_modules\\lzma-native\\binding-v6.0.1-n-api-win32-x64" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v115"
npm ERR! gyp ERR! cwd D:\work-space\Mercury\apps\node_modules\lzma-native
npm ERR! gyp ERR! node -v v20.0.0
npm ERR! gyp ERR! node-gyp -v v9.3.1
npm ERR! gyp ERR! not ok
npm ERR! node-pre-gyp ERR! build error
npm ERR! node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\a00572050\AppData\Roaming\nvm\v20.0.0\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=D:\work-space\Mercury\apps\node_modules\lzma-native\binding-v6.0.1-n-api-win32-x64\lzma_native.node --module_name=lzma_native --module_path=D:\work-space\Mercury\apps\node_modules\lzma-native\binding-v6.0.1-n-api-win32-x64 --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v115' (1)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (D:\work-space\Mercury\apps\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:511:28)
npm ERR! node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1098:16)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:304:5)
npm ERR! node-pre-gyp ERR! System Windows_NT 10.0.22621
npm ERR! node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\work-space\\Mercury\\apps\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
npm ERR! node-pre-gyp ERR! cwd D:\work-space\Mercury\apps\node_modules\lzma-native
npm ERR! node-pre-gyp ERR! node -v v20.0.0
npm ERR! node-pre-gyp ERR! node-pre-gyp -v v0.11.0
npm ERR! node-pre-gyp ERR! not ok

npm ERR! A complete log of this run can be found in: C:\Users\a00572050\AppData\Local\npm-cache\_logs\2024-06-24T07_37_23_567Z-debug-0.log
 ```

**Comment by patilbhupesh** [comment]
Finally, I found a solution for the above issue, which will work for me.

```
npm cache clean

nvm use 18.17.0

npm install 

or 

npm install --force

```
