### ISSUE TITLE
Cannot find prebuilt for linux on ARM: error 404

### ISSUE THREAD

**Issue by cyrilfr** [addaleax/lzma-native#144]
I try to build an app that uses lzma-native as a dependancy somewhere for a linux distro targetting a RPi (ARM). Thus it tries to build lzma-native but cannot find the prebuilt binary during `npm install`.

It's using lzma-native 6.0.1, building with node-pre-gyp 5.0.3 for node 10.17.0.

I'ts part of a long build process using [BitBake](https://docs.yoctoproject.org/bitbake/) recipes.

Here is the output:
```
| WARN Using request for node-pre-gyp https download
| node-pre-gyp WARN Tried to download(404): https://node-pre-gyp.addaleax.net/lzma-native/lzma_native-v6.0.1-n-api-linux-arm.tar.gz
| node-pre-gyp WARN Tried to download(404): https://node-pre-gyp.addaleax.net/lzma-native/lzma_native-v6.0.1-n-api-linux-arm.tar.gz
| node-pre-gyp WARN Pre-built binaries not found for lzma-native@6.0.1 and node@10.17.0 (node-v64 ABI, glibc) (falling back to source compile with node-gyp)
| 
| 
| node-pre-gyp WARN Pre-built binaries not found for lzma-native@6.0.1 and node@10.17.0 (node-v64 ABI, glibc) (falling back to source compile with node-gyp)
| gyp: Call to 'sh liblzma-config.sh "/yocto/poky/build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/vesta-app/3.6-r20/git/node_modules/lzma-native/build" "/yocto/poky/build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/vesta-app/3.6-r20/git/node_modules/lzma-native/deps/xz-5.2.3.tar.bz2"' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
| 
| gyp: Call to 'sh liblzma-config.sh "/yocto/poky/build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/vesta-app/3.6-r20/git/node_modules/lzma-native/build" "/yocto/poky/build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/vesta-app/3.6-r20/git/node_modules/lzma-native/deps/xz-5.2.3.tar.bz2"' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
| gyp
| gyp ERR! configure error
| 
| ERR! configure error
| gyp ERR!
| gyp ERR! stack Error: `gyp` failed with exit code: 1
| gyp ERR! stack     at ChildProcess.onCpExit (/yocto/poky/build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/vesta-app/3.6-r20/recipe-sysroot-native/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:344:16)
| gyp
|  stack Error: `gyp` failed with exit code: 1
| gyp ERR! stack     at ChildProcess.onCpExit (/yocto/poky/build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/vesta-app/3.6-r20/recipe-sysroot-native/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:344:16)
| gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
| gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
| 
|  ERR! stack     at ChildProcess.emit (events.js:198:13)
| gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
| gyp
| gyp ERR! System Linux 6.8.0-45-generic
| 
|  ERR! System Linux 6.8.0-45-generic
| gyp
| gyp ERR! command "/yocto/poky/build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/vesta-app/3.6-r20/recipe-sysroot-native/usr/bin/node" "/yocto/poky/build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/vesta-app/3.6-r20/recipe-sysroot-native/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/yocto/poky/build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/vesta-app/3.6-r20/git/node_modules/lzma-native/binding-v6.0.1-n-api-linux-arm/lzma_native.node" "--module_name=lzma_native" "--module_path=/yocto/poky/build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/vesta-app/3.6-r20/git/node_modules/lzma-native/binding-v6.0.1-n-api-linux-arm" "--napi_version=5" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v64"
| gyp
| ERR! command "/yocto/poky/build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/vesta-app/3.6-r20/recipe-sysroot-native/usr/bin/node" "/yocto/poky/build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/vesta-app/3.6-r20/recipe-sysroot-native/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/yocto/poky/build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/vesta-app/3.6-r20/git/node_modules/lzma-native/binding-v6.0.1-n-api-linux-arm/lzma_native.node" "--module_name=lzma_native" "--module_path=/yocto/poky/build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/vesta-app/3.6-r20/git/node_modules/lzma-native/binding-v6.0.1-n-api-linux-arm" "--napi_version=5" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v64"
| gyp ERR! cwd /yocto/poky/build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/vesta-app/3.6-r20/git/node_modules/lzma-native
| gyp ERR! node -v v10.17.0
| 
| ERR! cwd /yocto/poky/build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/vesta-app/3.6-r20/git/node_modules/lzma-native
| gyp ERR! node -v v10.17.0
| gyp ERR! node-gyp -v v5.0.3
| gyp
| gyp ERR! node-gyp -v v5.0.3
| gyp ERR! not ok
```

**Comment by cyrilfr** [comment]
Any news on that?

I tried with armv7l but same result => error 404.

**Comment by Leslie-Wong-H** [comment]
Running linux/arm64 at github action to target lzma-native compile is not OK. 

```
#26 [linux/arm64 7/9] RUN yarn install --frozen-lockfile --production
#26 3.031 yarn install v1.22.22
#26 3.359 (node:8) [DEP0169] DeprecationWarning: `url.parse()` behavior is not standardized and prone to errors that have security implications. Use the WHATWG URL API instead. CVEs are not issued for `url.parse()` vulnerabilities.
#26 3.359 (Use `node --trace-deprecation ...` to show where the warning was created)
#26 3.733 [1/4] Resolving packages...
#26 4.341 [2/4] Fetching packages...
#26 24.57 [3/4] Linking dependencies...
#26 30.01 [4/4] Building fresh packages...
#26 54.63 error /app/node_modules/lzma-native: Command failed.
#26 54.63 Exit code: 1
#26 54.63 Command: node-gyp-build
#26 54.63 Arguments: 
#26 54.63 Directory: /app/node_modules/lzma-native
#26 54.63 Output:
#26 54.63 gyp info it worked if it ends with ok
#26 54.63 gyp info using node-gyp@11.4.2
#26 54.63 gyp info using node@24.12.0 | linux | arm64
#26 54.63 gyp info find Python using Python version 3.9.2 found at "/usr/bin/python3"
#26 54.63 
#26 54.63 gyp http GET https://nodejs.org/download/release/v24.12.0/node-v24.12.0-headers.tar.gz
#26 54.63 gyp http 200 https://nodejs.org/download/release/v24.12.0/node-v24.12.0-headers.tar.gz
#26 54.63 gyp http GET https://nodejs.org/download/release/v24.12.0/SHASUMS256.txt
#26 54.63 gyp http 200 https://nodejs.org/download/release/v24.12.0/SHASUMS256.txt
#26 54.63 gyp info spawn /usr/bin/python3
#26 54.63 gyp info spawn args [
#26 54.63 gyp info spawn args '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
#26 54.63 gyp info spawn args 'binding.gyp',
#26 54.63 gyp info spawn args '-f',
#26 54.63 gyp info spawn args 'make',
#26 54.63 gyp info spawn args '-I',
#26 54.63 gyp info spawn args '/app/node_modules/lzma-native/build/config.gypi',
#26 54.63 gyp info spawn args '-I',
#26 54.63 gyp info spawn args '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
#26 54.63 gyp info spawn args '-I',
#26 54.63 gyp info spawn args '/root/.cache/node-gyp/24.12.0/include/node/common.gypi',
#26 54.63 gyp info spawn args '-Dlibrary=shared_library',
#26 54.63 gyp info spawn args '-Dvisibility=default',
#26 54.63 gyp info spawn args '-Dnode_root_dir=/root/.cache/node-gyp/24.12.0',
#26 54.63 gyp info spawn args '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
#26 54.63 gyp info spawn args '-Dnode_lib_file=/root/.cache/node-gyp/24.12.0/<(target_arch)/node.lib',
#26 54.63 gyp info spawn args '-Dmodule_root_dir=/app/node_modules/lzma-native',
#26 54.63 gyp info spawn args '-Dnode_engine=v8',
#26 54.63 gyp info spawn args '--depth=.',
#26 54.63 gyp info spawn args '--no-parallel',
#26 54.63 gyp info spawn args '--generator-output',
#26 54.63 gyp info spawn args 'build',
#26 54.63 gyp info spawn args '-Goutput_dir=.'
#26 54.63 gyp info spawn args ]
#26 54.63 gyp: Call to 'sh liblzma-config.sh "/app/node_modules/lzma-native/build" "/app/node_modules/lzma-native/deps/xz-5.2.3.tar.bz2"' returned exit status 2 while in binding.gyp. while trying to load binding.gyp
#26 54.63 gyp ERR! configure error 
#26 54.63 gyp ERR! stack Error: `gyp` failed with exit code: 1
#26 54.63 gyp ERR! stack at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:317:18)
#26 54.63 gyp ERR! stack at ChildProcess.emit (node:events:508:28)
#26 54.63 gyp ERR! stack at ChildProcess._handle.onexit (node:internal/child_process:294:12)
#26 54.63 gyp ERR! System Linux 6.11.0-1018-azure
#26 54.63 gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
#26 54.63 gyp ERR! cwd /app/node_modules/lzma-native
#26 54.63 gyp ERR! node -v v24.12.0
#26 54.63 gyp ERR! node-gyp -v v11.4.2
#26 54.63 gyp ERR! not ok
#26 54.63 info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
#26 ERROR: process "/bin/sh -c yarn install --frozen-lockfile --production" did not complete successfully: exit code: 1
------
 > [linux/arm64 7/9] RUN yarn install --frozen-lockfile --production:
54.63 gyp ERR! stack at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:317:18)
54.63 gyp ERR! stack at ChildProcess.emit (node:events:508:28)
54.63 gyp ERR! stack at ChildProcess._handle.onexit (node:internal/child_process:294:12)
54.63 gyp ERR! System Linux 6.11.0-1018-azure
54.63 gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
54.63 gyp ERR! cwd /app/node_modules/lzma-native
54.63 gyp ERR! node -v v24.12.0
54.63 gyp ERR! node-gyp -v v11.4.2
54.63 gyp ERR! not ok
54.63 info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
------
WARNING: local cache import at /tmp/.buildx-cache not found due to err: could not read /tmp/.buildx-cache/index.json: open /tmp/.buildx-cache/index.json: no such file or directory
```

**Comment by Leslie-Wong-H** [comment]
> Running linux/arm64 at github action to target lzma-native compile is not OK.
> 
> ```
> #26 [linux/arm64 7/9] RUN yarn install --frozen-lockfile --production
> #26 3.031 yarn install v1.22.22
> #26 3.359 (node:8) [DEP0169] DeprecationWarning: `url.parse()` behavior is not standardized and prone to errors that have security implications. Use the WHATWG URL API instead. CVEs are not issued for `url.parse()` vulnerabilities.
> #26 3.359 (Use `node --trace-deprecation ...` to show where the warning was created)
> #26 3.733 [1/4] Resolving packages...
> #26 4.341 [2/4] Fetching packages...
> #26 24.57 [3/4] Linking dependencies...
> #26 30.01 [4/4] Building fresh packages...
> #26 54.63 error /app/node_modules/lzma-native: Command failed.
> #26 54.63 Exit code: 1
> #26 54.63 Command: node-gyp-build
> #26 54.63 Arguments: 
> #26 54.63 Directory: /app/node_modules/lzma-native
> #26 54.63 Output:
> #26 54.63 gyp info it worked if it ends with ok
> #26 54.63 gyp info using node-gyp@11.4.2
> #26 54.63 gyp info using node@24.12.0 | linux | arm64
> #26 54.63 gyp info find Python using Python version 3.9.2 found at "/usr/bin/python3"
> #26 54.63 
> #26 54.63 gyp http GET https://nodejs.org/download/release/v24.12.0/node-v24.12.0-headers.tar.gz
> #26 54.63 gyp http 200 https://nodejs.org/download/release/v24.12.0/node-v24.12.0-headers.tar.gz
> #26 54.63 gyp http GET https://nodejs.org/download/release/v24.12.0/SHASUMS256.txt
> #26 54.63 gyp http 200 https://nodejs.org/download/release/v24.12.0/SHASUMS256.txt
> #26 54.63 gyp info spawn /usr/bin/python3
> #26 54.63 gyp info spawn args [
> #26 54.63 gyp info spawn args '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
> #26 54.63 gyp info spawn args 'binding.gyp',
> #26 54.63 gyp info spawn args '-f',
> #26 54.63 gyp info spawn args 'make',
> #26 54.63 gyp info spawn args '-I',
> #26 54.63 gyp info spawn args '/app/node_modules/lzma-native/build/config.gypi',
> #26 54.63 gyp info spawn args '-I',
> #26 54.63 gyp info spawn args '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
> #26 54.63 gyp info spawn args '-I',
> #26 54.63 gyp info spawn args '/root/.cache/node-gyp/24.12.0/include/node/common.gypi',
> #26 54.63 gyp info spawn args '-Dlibrary=shared_library',
> #26 54.63 gyp info spawn args '-Dvisibility=default',
> #26 54.63 gyp info spawn args '-Dnode_root_dir=/root/.cache/node-gyp/24.12.0',
> #26 54.63 gyp info spawn args '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
> #26 54.63 gyp info spawn args '-Dnode_lib_file=/root/.cache/node-gyp/24.12.0/<(target_arch)/node.lib',
> #26 54.63 gyp info spawn args '-Dmodule_root_dir=/app/node_modules/lzma-native',
> #26 54.63 gyp info spawn args '-Dnode_engine=v8',
> #26 54.63 gyp info spawn args '--depth=.',
> #26 54.63 gyp info spawn args '--no-parallel',
> #26 54.63 gyp info spawn args '--generator-output',
> #26 54.63 gyp info spawn args 'build',
> #26 54.63 gyp info spawn args '-Goutput_dir=.'
> #26 54.63 gyp info spawn args ]
> #26 54.63 gyp: Call to 'sh liblzma-config.sh "/app/node_modules/lzma-native/build" "/app/node_modules/lzma-native/deps/xz-5.2.3.tar.bz2"' returned exit status 2 while in binding.gyp. while trying to load binding.gyp
> #26 54.63 gyp ERR! configure error 
> #26 54.63 gyp ERR! stack Error: `gyp` failed with exit code: 1
> #26 54.63 gyp ERR! stack at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:317:18)
> #26 54.63 gyp ERR! stack at ChildProcess.emit (node:events:508:28)
> #26 54.63 gyp ERR! stack at ChildProcess._handle.onexit (node:internal/child_process:294:12)
> #26 54.63 gyp ERR! System Linux 6.11.0-1018-azure
> #26 54.63 gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
> #26 54.63 gyp ERR! cwd /app/node_modules/lzma-native
> #26 54.63 gyp ERR! node -v v24.12.0
> #26 54.63 gyp ERR! node-gyp -v v11.4.2
> #26 54.63 gyp ERR! not ok
> #26 54.63 info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
> #26 ERROR: process "/bin/sh -c yarn install --frozen-lockfile --production" did not complete successfully: exit code: 1
> ------
>  > [linux/arm64 7/9] RUN yarn install --frozen-lockfile --production:
> 54.63 gyp ERR! stack at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:317:18)
> 54.63 gyp ERR! stack at ChildProcess.emit (node:events:508:28)
> 54.63 gyp ERR! stack at ChildProcess._handle.onexit (node:internal/child_process:294:12)
> 54.63 gyp ERR! System Linux 6.11.0-1018-azure
> 54.63 gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
> 54.63 gyp ERR! cwd /app/node_modules/lzma-native
> 54.63 gyp ERR! node -v v24.12.0
> 54.63 gyp ERR! node-gyp -v v11.4.2
> 54.63 gyp ERR! not ok
> 54.63 info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
> ------
> WARNING: local cache import at /tmp/.buildx-cache not found due to err: could not read /tmp/.buildx-cache/index.json: open /tmp/.buildx-cache/index.json: no such file or directory
> ```

The context: https://github.com/shotit/shotit-worker/actions/runs/20697101430/job/59413984340 
and https://github.com/shotit/shotit-worker/blob/main/hasher.Dockerfile
