### ISSUE TITLE
Cannot find module 'nopt'

### ISSUE THREAD

**Issue by clemos** [addaleax/lzma-native#23]
Hi,
It seems your latest upgrade breaks (my?) installation : 
```
> lzma-native@1.5.0 install XXXX/node_modules/lzma-native
> node-pre-gyp install --fallback-to-build

module.js:327
    throw err;
    ^

Error: Cannot find module 'nopt'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (XXXX/node_modules/lzma-native/node_modules/node-pre-gyp/lib/node-pre-gyp.js:14:12)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
```
Maybe adding `nopt` as a dependency would be enough ?

**Comment by addaleax** [comment]
Hi, that’s weird and looks more like an npm bug or something that went wrong when publishing node-pre-pyp.

Can you show the output of `npm ls`? Which `npm`/`node` versions are you using? Can you run an argumentless `npm install`?

**Comment by addaleax** [comment]
It seems `npm@2` and `npm@3` handle bundled dependencies differently. I’ve just published 1.5.1, can you try that?

**Comment by clemos** [comment]
Yes, it seems to work, now :) thanks a lot !

**Comment by addaleax** [comment]
Thanks, let me know if anything else pops up! :)
