### ISSUE TITLE
Cannot find module when using electron.

### ISSUE THREAD

**Issue by dscalzi** [addaleax/lzma-native#36]
Hello, I am having an issue with the module, specifically trying to require it.

The following error is produced when running the line of code `const lzma = require('lzma-native')`

> Error: Cannot find module 'C:\Users\Asus\Desktop\LauncherElectron\node_modules\lzma-native\binding-v2.0.1-electron-v1.6-win32-x64\lzma_native.node'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (c:\Users\Asus\Desktop\LauncherElectron\node_modules\electron\dist\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at C:\Users\Asus\Desktop\LauncherElectron\node_modules\lzma-native\index.js:12:14
    at Object.<anonymous> (C:\Users\Asus\Desktop\LauncherElectron\node_modules\lzma-native\index.js:588:3)
    at Object.<anonymous> (C:\Users\Asus\Desktop\LauncherElectron\node_modules\lzma-native\index.js:590:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)

Contents of the lzma-native folder below:

https://i.gyazo.com/5f99254fc0bf05f2c13764fedf01709a.png

No clue why this is happening.

**Comment by addaleax** [comment]
Can you re-run `npm install` with `--runtime=electron --target=1.6`?

**Comment by addaleax** [comment]
I’m closing this due to lack of follow-up but please ping me if you’re still having trouble.

**Comment by oxygen** [comment]
I did `npm install lzma-native --save`

```JavaScript
const lzma = require("lzma-native");
```

```
App threw an error during load
Error: Cannot find module 'C:\ExportVHosts\DevApp\node_modules\lzma-native\binding-v3.0.1-electron-v1.7-win32-x64\lzma_native.node'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (C:\ExportVHosts\DevApp\node_modules\electron\dist\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at C:\ExportVHosts\DevApp\node_modules\lzma-native\index.js:13:14
    at Object.<anonymous> (C:\ExportVHosts\DevApp\node_modules\lzma-native\index.js:595:3)
    at Object.<anonymous> (C:\ExportVHosts\DevApp\node_modules\lzma-native\index.js:597:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\ExportVHosts\DevApp\src\node\classes\VMServer.js:17:14)
    at Object.<anonymous> (C:\ExportVHosts\DevApp\src\node\classes\VMServer.js:789:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```

**Comment by addaleax** [comment]
@oxygen Yeah, the second command seems about right. Does it work if you use the full version (including patch version) for `--target`? If the problem persists, can you open a separate issue?
