### ISSUE TITLE
Error: Cannot find module 'binding-v3.0.1-node-v57-darwin-x64'

### ISSUE THREAD

**Issue by OceanHorn** [addaleax/lzma-native#45]
Error occors when integrate realm to a react native app with version 2.0.2.
And there is no folder named 'binding-v3.0.1-node-v57-darwin-x64' existed in folder 'lzma-native'.

{ Error: Cannot find module '/Users/username/ReactNative/folder/Native/node_modules/lzma-native/binding-v3.0.1-node-v57-darwin-x64/lzma_native.node'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at /Users/username/ReactNative/folder/Native/node_modules/lzma-native/index.js:13:14
    at Object.<anonymous> (/Users/username/ReactNative/folder/Native/node_modules/lzma-native/index.js:595:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12) code: 'MODULE_NOT_FOUND' }

**Comment by addaleax** [comment]
What folders are there in `lzma-native`? Did `npm install lzma-native` succeed? Do you have any odd npm options like `ignore-scripts` activated?

**Comment by addaleax** [comment]
> Expired certificate had been replaced?

Yes, see #46 – I updated the cert but forgot to make the webserver reload its config. It’s a silly mistake on my end, but has been resolved now & shouldn’t happen again. :)

**Comment by esutton** [comment]
@addaleax  Thank you for sharing your work.

I think I will stick with yarn since it gives me a message "http certificate has expired" while npm did not.

**Comment by addaleax** [comment]
@esutton To be clear, the download of the pre-built binary happens using [node-pre-gyp](https://github.com/mapbox/node-pre-gyp), not in the package manager itself – I really can’t tell why npm vs yarn would make a difference here. It might just be that by the time you tried npm I had already fixed it? Anyway, go with whichever you prefer. :)

**Comment by esutton** [comment]
@addaleax That is true.  It might just have been timing.  Good point.  

I will stick with yarn since react-native uses it.

I need to make my own node.js package to learn more about how the things I use everyday actually work!

**Comment by OceanHorn** [comment]
@addaleax just `npm install`. 
 Files in folder `lzma-native` list below:
```
CHANGELOG.md
LICENSE
README.md
bin
binding-v1.5.3-node-v53-linux-x64
binding-v2.0.0-node-v53-linux-x64
binding-v2.0.1-node-v55-linux-x64
binding-v2.0.2-node-v55-linux-x64
binding-v2.0.3-node-v56-linux-x64
binding-v2.0.4-electron-v1.7-linux-x64
binding-v2.0.4-node-v48-linux-x64
binding-v2.0.4-node-v56-linux-x64
binding-v3.0.0-electron-v1.7-linux-x64
binding-v3.0.0-node-v56-linux-x64
binding-v3.0.1-node-v51-darwin-x64
binding-v3.0.1-node-v56-linux-x64
binding.gyp
cflags.sh
deps
index.js
liblzma-build.sh
liblzma-config.sh
node_modules
package.json
src
```

**Comment by addaleax** [comment]
Would still be nice to have an answer at least to “Did `npm install lzma-native` succeed?” … it looks like you might just have forgotten to rebuild after upgrading Node?

**Comment by OceanHorn** [comment]
@addaleax I tried to remove `lzma-native` and re-install by `npm install --save lzma-native`, logs like below:
```
> lzma-native@3.0.2 install /Users/OceanHorn/SourceTree/mmms/node_modules/lzma-native
> node-pre-gyp install --fallback-to-build && node node_modules/rimraf/bin.js build

[lzma-native] Success: "/Users/OceanHorn/SourceTree/mmms/node_modules/lzma-native/binding-v3.0.2-node-v51-darwin-x64/lzma_native.node" is installed via remote
mmms@0.0.1 /Users/guoyufu/SourceTree/mmms
├── UNMET PEER DEPENDENCY babel-eslint@8.0.2
├── UNMET PEER DEPENDENCY eslint-plugin-jest@^21.0.0
├── UNMET PEER DEPENDENCY eslint-plugin-jsx-a11y@^6.0.2
├── UNMET PEER DEPENDENCY eslint-plugin-relay@0.0.8
├─┬ lzma-native@3.0.2 
│ ├── nan@2.5.1 
│ ├─┬ node-pre-gyp@0.6.39 
│ │ ├── detect-libc@1.0.2 
│ │ ├─┬ hawk@3.1.3 
│ │ │ ├── boom@2.10.1 
│ │ │ ├── cryptiles@2.0.5 
│ │ │ ├── hoek@2.16.3 
│ │ │ └── sntp@1.0.9 
│ │ ├─┬ mkdirp@0.5.1 
│ │ │ └── minimist@0.0.8 
│ │ ├─┬ nopt@4.0.1 
│ │ │ ├── abbrev@1.1.1 
│ │ │ └─┬ osenv@0.1.4 
│ │ │   ├── os-homedir@1.0.2 
│ │ │   └── os-tmpdir@1.0.2 
│ │ ├─┬ npmlog@4.1.2 
│ │ │ ├─┬ are-we-there-yet@1.1.4 
│ │ │ │ └── delegates@1.0.0 
│ │ │ ├── console-control-strings@1.1.0 
│ │ │ ├─┬ gauge@2.7.4 
│ │ │ │ ├── aproba@1.2.0 
│ │ │ │ ├── has-unicode@2.0.1 
│ │ │ │ ├── object-assign@4.1.1 
│ │ │ │ ├── signal-exit@3.0.2 
│ │ │ │ ├─┬ string-width@1.0.2 
│ │ │ │ │ ├── code-point-at@1.1.0 
│ │ │ │ │ └─┬ is-fullwidth-code-point@1.0.0 
│ │ │ │ │   └── number-is-nan@1.0.1 
│ │ │ │ ├─┬ strip-ansi@3.0.1 
│ │ │ │ │ └── ansi-regex@2.1.1 
│ │ │ │ └── wide-align@1.1.2 
│ │ │ └── set-blocking@2.0.0 
│ │ ├─┬ rc@1.2.2 
│ │ │ ├── deep-extend@0.4.2 
│ │ │ ├── ini@1.3.4 
│ │ │ ├── minimist@1.2.0 
│ │ │ └── strip-json-comments@2.0.1 
│ │ ├─┬ request@2.81.0 
│ │ │ ├── aws-sign2@0.6.0 
│ │ │ ├── aws4@1.6.0 
│ │ │ ├── caseless@0.12.0 
│ │ │ ├─┬ combined-stream@1.0.5 
│ │ │ │ └── delayed-stream@1.0.0 
│ │ │ ├── extend@3.0.1 
│ │ │ ├── forever-agent@0.6.1 
│ │ │ ├─┬ form-data@2.1.4 
│ │ │ │ └── asynckit@0.4.0 
│ │ │ ├─┬ har-validator@4.2.1 
│ │ │ │ ├─┬ ajv@4.11.8 
│ │ │ │ │ ├── co@4.6.0 
│ │ │ │ │ └─┬ json-stable-stringify@1.0.1 
│ │ │ │ │   └── jsonify@0.0.0 
│ │ │ │ └── har-schema@1.0.5 
│ │ │ ├─┬ http-signature@1.1.1 
│ │ │ │ ├── assert-plus@0.2.0 
│ │ │ │ ├─┬ jsprim@1.4.1 
│ │ │ │ │ ├── assert-plus@1.0.0 
│ │ │ │ │ ├── extsprintf@1.3.0 
│ │ │ │ │ ├── json-schema@0.2.3 
│ │ │ │ │ └─┬ verror@1.10.0 
│ │ │ │ │   └── assert-plus@1.0.0 
│ │ │ │ └─┬ sshpk@1.13.1 
│ │ │ │   ├── asn1@0.2.3 
│ │ │ │   ├── assert-plus@1.0.0 
│ │ │ │   ├── bcrypt-pbkdf@1.0.1 
│ │ │ │   ├─┬ dashdash@1.14.1 
│ │ │ │   │ └── assert-plus@1.0.0 
│ │ │ │   ├── ecc-jsbn@0.1.1 
│ │ │ │   ├─┬ getpass@0.1.7 
│ │ │ │   │ └── assert-plus@1.0.0 
│ │ │ │   ├── jsbn@0.1.1 
│ │ │ │   └── tweetnacl@0.14.5 
│ │ │ ├── is-typedarray@1.0.0 
│ │ │ ├── isstream@0.1.2 
│ │ │ ├── json-stringify-safe@5.0.1 
│ │ │ ├─┬ mime-types@2.1.17 
│ │ │ │ └── mime-db@1.30.0 
│ │ │ ├── oauth-sign@0.8.2 
│ │ │ ├── performance-now@0.2.0 
│ │ │ ├── qs@6.4.0 
│ │ │ ├── stringstream@0.0.5 
│ │ │ ├─┬ tough-cookie@2.3.3 
│ │ │ │ └── punycode@1.4.1 
│ │ │ ├── tunnel-agent@0.6.0 
│ │ │ └── uuid@3.1.0 
│ │ ├── semver@5.4.1 
│ │ ├─┬ tar@2.2.1 
│ │ │ ├── block-stream@0.0.9 
│ │ │ └─┬ fstream@1.0.11 
│ │ │   └── graceful-fs@4.1.11 
│ │ └─┬ tar-pack@3.4.1 
│ │   ├─┬ debug@2.6.9 
│ │   │ └── ms@2.0.0 
│ │   ├── fstream-ignore@1.0.5 
│ │   ├─┬ once@1.4.0 
│ │   │ └── wrappy@1.0.2 
│ │   └── uid-number@0.0.6 
│ ├─┬ readable-stream@2.3.3 
│ │ ├── core-util-is@1.0.2 
│ │ ├── inherits@2.0.3 
│ │ ├── isarray@1.0.0 
│ │ ├── process-nextick-args@1.0.7 
│ │ ├── safe-buffer@5.1.1 
│ │ ├── string_decoder@1.0.3 
│ │ └── util-deprecate@1.0.2 
│ └─┬ rimraf@2.6.2 
│   └─┬ glob@7.1.2 
│     ├── fs.realpath@1.0.0 
│     ├── inflight@1.0.6 
│     ├─┬ minimatch@3.0.4 
│     │ └─┬ brace-expansion@1.1.8 
│     │   ├── balanced-match@1.0.0 
│     │   └── concat-map@0.0.1 
│     └── path-is-absolute@1.0.1 
├── UNMET PEER DEPENDENCY react@16.0.0-alpha.12
└── UNMET PEER DEPENDENCY react-native-elements@0.17.0

......
```

And the files in folder `./node_modules/lzma-native` list below:
```
CHANGELOG.md
LICENSE
README.md
README.md.xz
bin
binding-v3.0.1-node-v58-linux-x64
binding-v3.0.1-node-v59-linux-x64
binding-v3.0.2-node-v51-darwin-x64
binding.gyp
cflags.sh
deps
index.js
liblzma-build.sh
liblzma-config.sh
node_modules
package.json
src
```
I meet some network error in downloading `realm-sync-cocoa-2.1.1.tar.xz` now. I will give you more information later. Thanks a lot!

**Comment by esutton** [comment]
I too am using **realm** and saw an error regarding network error regarding **realm-sync-cocoa-2.1.1.tar.xz**

**Comment by Nitroman605** [comment]
is  ` https://node-pre-gyp.entless.org/lzma-native/lzma_native-v3.0.1-node-v57-win32-x64.tar.gz ` Down or something ? 

npm install used to work find and today I am getting this 


`node-pre-gyp ERR! Tried to download(undefined): https://node-pre-gyp.entless.org/lzma-native/lzma_native-v3.0.1-node-v57-win32-x64.tar.gz`


I checked the link and it's dead . Is anyone else having the same issue ?

**Comment by esutton** [comment]
I do not understand this.  Today I have had this problem off an on again.  I git clone, then yarn and all is good.  Then an hour later bad, then good, then bad....

I am using the realm package which I suspect indirectly depends on lzma-native

````
edwards-mbp:source edward3$ yarn
yarn install v1.3.2
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning " > react-native-firebase@3.0.0-alpha.3" has unmet peer dependency "fbjs@*".
warning " > react-test-renderer@16.0.0" has incorrect peer dependency "react@^16.0.0-beta.5".
[4/4] 📃  Building fresh packages...
[-/8] ⠈ waiting...
[2/8] ⠈ lzma-native: http GET https://node-pre-gyp.entless.org/lzma-nativ
[-/8] ⠈ waiting...
[4/8] ⠈ fsevents: https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1
warning Error running install script for optional dependency: "/Users/edward3/Documents/projects/react-native/field-scout/source/node_modules/fsevents: Command failed.\nExit code: 1\nCommand: node install\nArguments: \nDirectory: /Users/edward3/Documents/projects/react-native/field-scout/source/node_modules/fsevents\nOutput:\nnode-pre-gyp info it worked if it ends with ok\nnode-pre-gyp info using node-pre-gyp@0.6.36\nnode-pre-gyp info using node@8.9.0 | darwin | x64\nnode-pre-gyp info check checked for \"/Users/edward3/Documents/projects/react-native/field-scout/source/node_modules/fsevents/lib/binding/Release/node-v57-darwin-x64/fse.node\" (not found)\nnode-pre-gyp http GET https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.1/fse-v1.1.1-node-v57-darwin-x64.tar.gz\nnode-pre-gyp http 404 https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.1/fse-v1.1.1-node-v57-darwin-x64.tar.gz\nnode-pre-gyp ERR! Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.1/fse-v1.1.1-node-v57-darwin-x64.tar.gz \nnode-pre-gyp ERR! Pre-built binaries not found for fsevents@1.1.1 and node@8.9.0 (node-v57 ABI) (falling back to source compile with node-gyp) \nnode-pre-gyp http 404 status code downloading tarball https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.1/fse-v1.1.1-node-v57-darwin-x64.tar.gz \nnode-pre-gyp ERR! build error \nnode-pre-gyp ERR! stack Error: Failed to execute 'node-gyp clean' (Error: spawn node-gyp ENOENT)\nnode-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/edward3/Documents/projects/react-native/field-scout/source/node_modules/node-pre-gyp/lib/util/compile.js:77:29)\nnode-pre-gyp ERR! stack     at emitOne (events.js:116:13)\nnode-pre-gyp ERR! stack     at ChildProcess.emit (events.js:211:7)\nnode-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:196:12)\nnode-pre-gyp ERR! stack     at onErrorNT (internal/child_process.js:372:16)\nnode-pre-gyp ERR! stack     at _combinedTickCallback (internal/process/next_tick.js:138:11)\nnode-pre-gyp ERR! stack     at process._tickCallback (internal/process/next_tick.js:180:9)\nnode-pre-gyp ERR! System Darwin 16.7.0\nnode-pre-gyp ERR! command \"/usr/local/Cellar/node/8.9.0/bin/node\" \"/Users/edward3/Documents/projects/react-native/field-scout/source/node_modules/fsevents/node_modules/.bin/node-pre-gyp\" \"install\" \"--fallback-to-build\"\nnode-pre-gyp ERR! cwd /Users/edward3/Documents/p$ echo hello from yarn postinstall && scripts/npm-post-install.sh
````

**Comment by addaleax** [comment]
@esutton I’m not sure but it sounds like that is not an issue with the lzma-native part? The last line of that message reads:

```js
warning Error running install script for optional dependency: "/Users/edward3/Documents/projects/react-native/field-scout/source/node_modules/fsevents: Command failed.
Exit code: 1
Command: node install
Arguments: 
Directory: /Users/edward3/Documents/projects/react-native/field-scout/source/node_modules/fsevents
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.6.36
node-pre-gyp info using node@8.9.0 | darwin | x64
node-pre-gyp info check checked for \"/Users/edward3/Documents/projects/react-native/field-scout/source/node_modules/fsevents/lib/binding/Release/node-v57-darwin-x64/fse.node\" (not found)
node-pre-gyp http GET https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.1/fse-v1.1.1-node-v57-darwin-x64.tar.gz
node-pre-gyp http 404 https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.1/fse-v1.1.1-node-v57-darwin-x64.tar.gz
node-pre-gyp ERR! Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.1/fse-v1.1.1-node-v57-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.1.1 and node@8.9.0 (node-v57 ABI) (falling back to source compile with node-gyp) 
node-pre-gyp http 404 status code downloading tarball https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.1/fse-v1.1.1-node-v57-darwin-x64.tar.gz 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp clean' (Error: spawn node-gyp ENOENT)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/edward3/Documents/projects/react-native/field-scout/source/node_modules/node-pre-gyp/lib/util/compile.js:77:29)
node-pre-gyp ERR! stack     at emitOne (events.js:116:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:211:7)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:196:12)
node-pre-gyp ERR! stack     at onErrorNT (internal/child_process.js:372:16)
node-pre-gyp ERR! stack     at _combinedTickCallback (internal/process/next_tick.js:138:11)
node-pre-gyp ERR! stack     at process._tickCallback (internal/process/next_tick.js:180:9)
node-pre-gyp ERR! System Darwin 16.7.0
node-pre-gyp ERR! command \"/usr/local/Cellar/node/8.9.0/bin/node\" \"/Users/edward3/Documents/projects/react-native/field-scout/source/node_modules/fsevents/node_modules/.bin/node-pre-gyp\" \"install\" \"--fallback-to-build\"
node-pre-gyp ERR! cwd /Users/edward3/Documents/p$ echo hello from yarn postinstall && scripts/npm-post-install.sh
```

I think all of that is coming from `fsevents`…

**Comment by esutton** [comment]
@addaleax I expect you are right. Thanks for looking at it.
