### ISSUE TITLE
node-pre-gyp.entless.org has an invalid certificate

### ISSUE THREAD

**Issue by bjlaub** [addaleax/lzma-native#46]
This code: https://github.com/addaleax/lzma-native/blob/master/package.json#L55-L60
tells node-gyp to download pre-built binaries from https://node-pre-gyp.entless.org, but it seems like that host has a certificate that is expired, or is otherwise invalid.

```
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.6.38
node-pre-gyp info using node@8.6.0 | darwin | x64
node-pre-gyp info check checked for "***/node_modules/lzma-native/binding-v3.0.1-node-v57-darwin-x64/lzma_native.node" (not found)
node-pre-gyp http GET https://node-pre-gyp.entless.org/lzma-native/lzma_native-v3.0.1-node-v57-darwin-x64.tar.gz
node-pre-gyp ERR! Tried to download(undefined): https://node-pre-gyp.entless.org/lzma-native/lzma_native-v3.0.1-node-v57-darwin-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for lzma-native@3.0.1 and node@8.6.0 (node-v57 ABI) (falling back to source compile with node-gyp)
node-pre-gyp http certificate has expired
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp clean' (Error: spawn node-gyp ENOENT)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (***/node_modules/node-pre-gyp/lib/util/compile.js:77:29)
node-pre-gyp ERR! stack     at emitOne (events.js:115:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:210:7)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
node-pre-gyp ERR! stack     at onErrorNT (internal/child_process.js:374:16)
node-pre-gyp ERR! stack     at _combinedTickCallback (internal/process/next_tick.js:138:11)
node-pre-gyp ERR! stack     at process._tickCallback (internal/process/next_tick.js:180:9)
node-pre-gyp ERR! System Darwin 16.7.0
node-pre-gyp ERR! command "/usr/local/Cellar/node/8.6.0/bin/node" "***/node_modules/lzma-native/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
```
<img width="583" alt="screen shot 2017-11-07 at 5 06 59 pm" src="https://user-images.githubusercontent.com/3256070/32520483-2e34d316-c3de-11e7-9543-389f10508617.png">

**Comment by addaleax** [comment]
Ugh. Yes. I did the cert update, but forgot to reload the webserver config… sigh. Anyway, should be fixed now, thanks for the report!

**Comment by bjlaub** [comment]
woot, thanks @addaleax!
