### ISSUE TITLE
Windows support ?

### ISSUE THREAD

**Issue by mouda3** [addaleax/lzma-native#5]
When i'm trying to install this package on windows i'm getting a node-gyp error when calling 'sh liblzma-config.sh ...'.

```
if not defined npm_config_node_gyp (node "C:\Program Files\NodeJS\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
'sh' is not recognized as an internal or external command,
operable program or batch file.
gyp: Call to 'sh liblzma-config.sh C:\Users\fatim\Desktop\BUILD\node_modules\lzma-native/build C:\Users\fatim\Desktop\BUILD\node_modules\lzma-native/deps/xz-5.2.1.tar.bz2' returned exit status 1. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Program Files\NodeJS\node_modules\npm\node_modules\node-gyp\lib\configure.js:355:16)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "C:\\Program Files\\NodeJS\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\fatim\Desktop\BUILD\node_modules\lzma-native
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\NodeJS\\\\node.exe" "C:\\Program Files\\NodeJS\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE

npm ERR! lzma-native@0.2.13 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the lzma-native@0.2.13 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the lzma-native package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls lzma-native
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\fatim\Desktop\BUILD\npm-debug.log
```

**Comment by addaleax** [comment]
I’ll have a look at this the next time I’m near a Windows machine, but I can’t guarantee anything – Building the native package has required *sh for a long time now, and although `liblzma` can now supposedly be built using MSVC2013, I have never used it and I can’t really say how it would integrate into the build process for node modules.

I don’t know if you have the option of using a system which provides bash or similar (e.g. MinGW + MSYS or cygwin), but I’d say that that is currently your best shot for making this work.
You should feel free to look into the implementations I listed under [Related Projects](https://github.com/addaleax/lzma-native#related-projects) in the readme. But as far as I can tell, all of the other native implementations either build the native library from the source (running into the same problems as this module does) or use pre-compiled liblzma libraries and therefore won’t work under Windows.

You can always go for one of the non-native implementations listed there, which exclusively use JS.

**Comment by gagern** [comment]
In other projects (libxmljs in particular) I've seen the following: configure is run by the maintainer, then the resulting `config.h` is shipped with the sources, while the Makefile gets adapted to a gyp file. Some other projects even ship one `config.h` per target OS. The benefit is that this does not depen on sh or any of the other tools common on *nix but missing on Windows. The downside is that this offers no site-specific detection of build environment. Which means no automagically choosen set of feature, but also no automatic tweaks to adapt to various environments. Not sure how much lzma actually needs auto-configuration, but perhaps that would be an option.

**Comment by addaleax** [comment]
Ok, thanks for the pointer – I will try that the next time I’m using Windows somewhere (unless you have a burning desire to do this yourself :))

**Comment by mouda3** [comment]
Hi, thanks for your help :D. Actually after trying some non-native solutions my process always crashes on both OS X and Windows ( Node process consuming a lot of memory ) when i'm feeding it a file to compress and its just too slow. Also tried using Cygwin but i'm getting the same 'sh liblzma-config.sh path' error ... .
Talking about path, I also had an issue with installing this package on OS X when the path had a space in it.

**Comment by addaleax** [comment]
Regarding the path issue: Yes, that’s unexpected and bad, but I’m afraid that’s something one has to live with for now. It is neither directly related to this npm module nor to xz-utils; It is a problem within libtool and has been known to them since [at least 2007, with no intention to fix](https://lists.gnu.org/archive/html/bug-automake/2007-10/msg00000.html). Sigh.

**Comment by addaleax** [comment]
@mouda3 Could you check if things work now? I tried to add Windows support in 0.3.5, but since I only had Appveyor available for testing, I’d like to be sure before I close this. :)

**Comment by mouda3** [comment]
So after reinstalling python 2.7.10 and VS 2015 ( for node-gyp ), i tried installing your package on my Windows 10 x64 computer. It starts building but dies afterwards on this error :
```
> if not defined npm_config_node_gyp (node "C:\Program Files\NodeJS\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
Warning: Missing input files:
C:\Users\mouda\Desktop\New folder\node_modules\lzma-native\build\..\deps\doc\liblzma.def
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  build
  Microsoft (R) Library Manager Version 14.00.23026.0
  Copyright (C) Microsoft Corporation.  All rights reserved.

LINK : fatal error LNK1181: cannot open input file 'folder\node_modules\lzma-na
tive\deps\doc\liblzma.def' [C:\Users\mouda\Desktop\New folder\node_modules\lzma
-native\build\liblzma.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\NodeJS\node_modules\npm\node_modules\node-gyp\lib\build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "C:\\Program Files\\NodeJS\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\mouda\Desktop\New folder\node_modules\lzma-native
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\NodeJS\\\\node.exe" "C:\\Program Files\\NodeJS\\node_modules\\npm\\bin\\npm-cli.js" "install" "lzma-native"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE
```

**Comment by addaleax** [comment]
Thank you! I was somewhat confused by the npm docs regarding the handling of `.npmignore` files, but I’m pretty sure this problem is fixed now and everything necessary for compiling is included in the published files in 0.3.6. Could you try again?

**Comment by mouda3** [comment]
Retried but with no luck ... same problem : 
```
> if not defined npm_config_node_gyp (node "C:\Program Files\NodeJS\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  build
  Microsoft (R) Library Manager Version 14.00.23026.0
  Copyright (C) Microsoft Corporation.  All rights reserved.

LINK : fatal error LNK1181: cannot open input file 'folder\node_modules\lzma-native\deps\doc\liblzma.def' [C:\Users\mouda\Desktop\New folder\node_modules\lzma-native\bui ld\liblzma.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\NodeJS\node_modules\npm\node_modules\node-gyp\lib\build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "C:\\Program Files\\NodeJS\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\mouda\Desktop\New folder\node_modules\lzma-native
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\NodeJS\\\\node.exe" "C:\\Program Files\\NodeJS\\node_modules\\npm\\bin\\npm-cli.js" "install" "lzma-native"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE

npm ERR! lzma-native@0.3.6 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the lzma-native@0.3.6 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the lzma-native package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls lzma-native
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\mouda\Desktop\New folder\npm-debug.log
```

**Comment by mouda3** [comment]
I forgot about the space in the path issue that was what keeping it from building, Now i'm getting a new error  ( cp linux command ) : 
```
> if not defined npm_config_node_gyp (node "C:\Program Files\NodeJS\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  build
  Microsoft (R) Library Manager Version 14.00.23026.0
  Copyright (C) Microsoft Corporation.  All rights reserved.

     Creating library C:\Users\mouda\Desktop\Newfolder\node_modules\lzma-native\deps\bin_x86-64\lzma.lib and object C:\Users\mouda
  \Desktop\Newfolder\node_modules\lzma-native\deps\bin_x86-64\lzma.exp
  'cp' is not recognized as an internal or external command,
  operable program or batch file.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(171,5): error MSB6006: "cmd.exe" exited with co
de 9009. [C:\Users\mouda\Desktop\Newfolder\node_modules\lzma-native\build\liblzma.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\NodeJS\node_modules\npm\node_modules\node-gyp\lib\build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "C:\\Program Files\\NodeJS\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\mouda\Desktop\Newfolder\node_modules\lzma-native
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\NodeJS\\\\node.exe" "C:\\Program Files\\NodeJS\\node_modules\\npm\\bin\\npm-cli.js" "install" "lzma-native"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE
```

**Comment by addaleax** [comment]
Oh, yeah, I see… I replaced it with `copy`, that should work. Could you try installing via `npm install git+https://github.com/addaleax/lzma-native.git` or the like, so the version does not need to be increased? :) And really, thank you for testing this!

**Comment by mouda3** [comment]
Well after now I'm getting missing input files, something went wrong when you tried to fix the path issue ?
 
```
> if not defined npm_config_node_gyp (node "C:\Program Files\NodeJS\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
Warning: Missing input files:
C:\Users\mouda\Desktop\Newfolder\node_modules\lzma-native\build\..\deps\doc\liblzma.def
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  build
  Microsoft (R) Library Manager Version 14.00.23026.0
  Copyright (C) Microsoft Corporation.  All rights reserved.

LINK : fatal error LNK1104: cannot open file 'C:\Users\mouda\Desktop\Newfolder\node_modules\lzma-native\deps\doc\liblzma.def' [C:\ Users\mouda\Desktop\Newfolder\node_modules\lzma-native\build\liblzma.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\NodeJS\node_modules\npm\node_modules\node-gyp\lib\build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "C:\\Program Files\\NodeJS\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\mouda\Desktop\Newfolder\node_modules\lzma-native
```

**Comment by addaleax** [comment]
Ah, sorry. I guess this because installing via git does not run `npm prepublish`… It might be easiest if you could `git clone npm https://github.com/addaleax/lzma-native.git` this repository and then run `npm install && npm test` from inside it. Would that be possible? If not, I’ll just publish again

**Comment by mouda3** [comment]
Well i was installing with `npm install https://git@github.com/addaleax/lzma-native.git` ... tried your way i get the same error : 
```
> npm install && npm test
|
> lzma-native@0.3.7 install C:\Users\mouda\Desktop\Newfolder\lzma-native
> node-gyp rebuild

> if not defined npm_config_node_gyp (node "C:\Program Files\NodeJS\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
Warning: Missing input files:
C:\Users\mouda\Desktop\Newfolder\lzma-native\build\..\deps\doc\liblzma.def
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  build
  Microsoft (R) Library Manager Version 14.00.23026.0
  Copyright (C) Microsoft Corporation.  All rights reserved.

LINK : fatal error LNK1104: cannot open file 'C:\Users\mouda\Desktop\Newfolder\lzma-native\deps\doc\liblzma.def' [C:\Users\mouda\D esktop\Newfolder\lzma-native\build\liblzma.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\NodeJS\node_modules\npm\node_modules\node-gyp\lib\build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "C:\\Program Files\\NodeJS\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\mouda\Desktop\Newfolder\lzma-native
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\NodeJS\\\\node.exe" "C:\\Program Files\\NodeJS\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE
npm ERR! lzma-native@0.3.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
```

**Comment by addaleax** [comment]
Okaaay… seems like running `npm run prepublish && npm install && npm test` might do the trick… which would be weird, since (purportedly) `npm install` without arguments runs the `prepublish` script. If that does not work, I will just publish 0.3.7.

**Comment by mouda3** [comment]
No 7zip  after running `npm run prepublish && npm install && npm test`

```
> lzma-native@0.3.7 prepublish C:\Users\mouda\Desktop\Newfolder\lzma-native
> cd deps && 7z x -y xz-5.2.1-windows.7z bin_i686/liblzma.dll bin_x86-64/liblzma.dll include doc/liblzma.def

'7z' is not recognized as an internal or external command,
operable program or batch file.

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\NodeJS\\\\node.exe" "C:\\Program Files\\NodeJS\\node_modules\\npm\\bin\\npm-cli.js" "run" "prepublish"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE
npm ERR! lzma-native@0.3.7 prepublish: `cd deps && 7z x -y xz-5.2.1-windows.7z bin_i686/liblzma.dll bin_x86-64/liblzma.dll include doc/liblzma.def`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the lzma-native@0.3.7 prepublish script 'cd deps && 7z x -y xz-5.2.1-windows.7z bin_i686/liblzma.dll bin_x86-64/liblzma.dll include doc/liblzma.def'.
npm ERR! This is most likely a problem with the lzma-native package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cd deps && 7z x -y xz-5.2.1-windows.7z bin_i686/liblzma.dll bin_x86-64/liblzma.dll include doc/liblzma.def
npm ERR! You can get their info via:
npm ERR!     npm owner ls lzma-native
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\mouda\Desktop\Newfolder\lzma-native\npm-debug.log
```

**Comment by addaleax** [comment]
Okay, you can install 7z if you want, but I just published 0.3.7 (a little optimistically, but in the worst case I’ll just re-publish), so you can try out the “regular” way

**Comment by mouda3** [comment]
Finally, it works fine ! Thanks and keep up the good work :D

**Comment by addaleax** [comment]
Okay, great! Thank you for testing so patiently! :)
