### ISSUE TITLE
Cannot find module 'binding-v3.0.1-node-v51-darwin-x64/lzma_native.node'

### ISSUE THREAD

**Issue by duguying** [addaleax/lzma-native#50]
```
Extracting realm-sync-cocoa-2.1.10.tar.xz => /Users/duguying/code/opsapp/node_modules/realm/vendor/realm-ios
{ Error: Cannot find module '/Users/duguying/code/opsapp/node_modules/realm/node_modules/lzma-native/binding-v3.0.1-node-v51-darwin-x64/lzma_native.node'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
```

**Comment by addaleax** [comment]
Can you provide any commands to reproduce this issue?

**Comment by duguying** [comment]
Xcode Version 9.2 (9C40b)

```
    /bin/sh -c /Users/duguying/Library/Developer/Xcode/DerivedData/opsapp-acegzusvpuxuqxbrwnjnkaepohws/Build/Intermediates.noindex/RealmJS.build/Debug-iphoneos/RealmJS.build/Script-F63FF2C51C12462600B3B8E0.sh

v7.10.0 is already installed.
Now using node v7.10.0 (npm v4.2.0)
Resolved requirements: { SYNC_SERVER_FOLDER: 'sync',
  SYNC_ARCHIVE: 'realm-sync-cocoa-2.1.10.tar.xz',
  SYNC_ARCHIVE_ROOT: 'core' }
No lockfile found at the target, proceeding.
Extracting realm-sync-cocoa-2.1.10.tar.xz => /Users/duguying/code/opsapp/node_modules/realm/vendor/realm-ios
{ Error: Cannot find module '/Users/duguying/code/opsapp/node_modules/realm/node_modules/lzma-native/binding-v3.0.1-node-v51-darwin-x64/lzma_native.node'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at /Users/duguying/code/opsapp/node_modules/realm/node_modules/lzma-native/index.js:13:14
    at Object.<anonymous> (/Users/duguying/code/opsapp/node_modules/realm/node_modules/lzma-native/index.js:595:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12) code: 'MODULE_NOT_FOUND' }
Command /bin/sh failed with exit code 1
```

it seems Xcode Version 9.2 (9C40b) using node v7.10.0, could you support this version.

**Comment by addaleax** [comment]
@duguying Node 7 has been unsupported for half a year now and is missing critical security fixes, so you really should not be using it.

Building the prebuilt binaries for this library on Travis already takes forever, so I would prefer not to add old, unsupported versions into the build matrix.

**Comment by duguying** [comment]
I've goto `https://node-pre-gyp.addaleax.net/lzma-native/` and download my version v3.0.1-node-v51-darwin-x64 and solved it.
