### ISSUE TITLE
Installation fails with `sudo npm install -g`

### ISSUE THREAD

**Issue by ilg-ul** [addaleax/lzma-native#55]
On macOS:

```console
$ sudo npm install -g lzma-native --verbose
Password:
npm info it worked if it ends with ok
npm verb cli [ '/usr/local/bin/node',
npm verb cli   '/usr/local/bin/npm',
npm verb cli   'install',
npm verb cli   '-g',
npm verb cli   'lzma-native',
npm verb cli   '--verbose' ]
npm info using npm@5.8.0
npm info using node@v9.10.1
npm verb npm-session 5fe0ffa2a6ae399c
npm http fetch GET 200 https://registry.npmjs.org/lzma-native 40ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/nan 312ms (from cache)
npm verb correctMkdir /Users/ilg/.npm/_locks correctMkdir not in flight; initializing
npm verb lock using /Users/ilg/.npm/_locks/staging-3a08f0df5026584d.lock for /usr/local/lib/node_modules/.staging
npm info lifecycle lzma-native@3.0.7~preuninstall: lzma-native@3.0.7
npm info lifecycle lzma-native@3.0.7~uninstall: lzma-native@3.0.7
npm verb unbuild rmStuff lzma-native@3.0.7 from /usr/local/lib/node_modules
npm info lifecycle lzma-native@3.0.7~postuninstall: lzma-native@3.0.7
npm info lifecycle lzma-native@3.0.7~preinstall: lzma-native@3.0.7
npm info linkStuff lzma-native@3.0.7
npm verb linkBins lzma-native@3.0.7
npm verb linkBins [ { lzmajs: './bin/lzmajs' }, '/usr/local/bin', true ]
npm verb linkMans lzma-native@3.0.7
/usr/local/bin/lzmajs -> /usr/local/lib/node_modules/lzma-native/bin/lzmajs
npm info lifecycle lzma-native@3.0.7~install: lzma-native@3.0.7

> lzma-native@3.0.7 install /usr/local/lib/node_modules/lzma-native
> node-pre-gyp install --fallback-to-build && node node_modules/rimraf/bin.js build

node-pre-gyp info it worked if it ends with ok
node-pre-gyp verb cli [ '/usr/local/bin/node',
node-pre-gyp verb cli   '/usr/local/lib/node_modules/lzma-native/node_modules/.bin/node-pre-gyp',
node-pre-gyp verb cli   'install',
node-pre-gyp verb cli   '--fallback-to-build' ]
node-pre-gyp info using node-pre-gyp@0.6.39
node-pre-gyp info using node@9.10.1 | darwin | x64
node-pre-gyp verb command install []
node-pre-gyp info check checked for "/usr/local/lib/node_modules/lzma-native/binding-v3.0.7-node-v59-darwin-x64/lzma_native.node" (not found)
node-pre-gyp http GET https://node-pre-gyp.addaleax.net/lzma-native/lzma_native-v3.0.7-node-v59-darwin-x64.tar.gz
node-pre-gyp ERR! Tried to download(undefined): https://node-pre-gyp.addaleax.net/lzma-native/lzma_native-v3.0.7-node-v59-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for lzma-native@3.0.7 and node@9.10.1 (node-v59 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp http EACCES: permission denied, mkdir '/usr/local/lib/node_modules/lzma-native/binding-v3.0.7-node-v59-darwin-x64' 
node-pre-gyp verb command build [ 'rebuild' ]
node-pre-gyp http 200 https://node-pre-gyp.addaleax.net/lzma-native/lzma_native-v3.0.7-node-v59-darwin-x64.tar.gz
gyp info it worked if it ends with ok
gyp verb cli [ '/usr/local/bin/node',
gyp verb cli   '/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'clean' ]
gyp info using node-gyp@3.6.2
gyp info using node@9.10.1 | darwin | x64
gyp verb command clean []
gyp verb clean removing "build" directory
gyp info ok 
gyp info it worked if it ends with ok
gyp verb cli [ '/usr/local/bin/node',
gyp verb cli   '/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'configure',
gyp verb cli   '--fallback-to-build',
gyp verb cli   '--module=/usr/local/lib/node_modules/lzma-native/binding-v3.0.7-node-v59-darwin-x64/lzma_native.node',
gyp verb cli   '--module_name=lzma_native',
gyp verb cli   '--module_path=/usr/local/lib/node_modules/lzma-native/binding-v3.0.7-node-v59-darwin-x64' ]
gyp info using node-gyp@3.6.2
gyp info using node@9.10.1 | darwin | x64
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/usr/local/lib/node_modules/npm/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/usr/local/lib/node_modules/npm/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/usr/local/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /usr/local/lib/node_modules/npm/node_modules/which/which.js:89:16
gyp verb `which` failed     at /usr/local/lib/node_modules/npm/node_modules/which/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /usr/local/lib/node_modules/npm/node_modules/which/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:170:21)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/usr/local/lib/node_modules/npm/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/usr/local/lib/node_modules/npm/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/usr/local/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /usr/local/lib/node_modules/npm/node_modules/which/which.js:89:16
gyp verb `which` failed     at /usr/local/lib/node_modules/npm/node_modules/which/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /usr/local/lib/node_modules/npm/node_modules/which/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:170:21)
gyp verb `which` failed   stack: 'Error: not found: python2\n    at getNotFoundError (/usr/local/lib/node_modules/npm/node_modules/which/which.js:13:12)\n    at F (/usr/local/lib/node_modules/npm/node_modules/which/which.js:68:19)\n    at E (/usr/local/lib/node_modules/npm/node_modules/which/which.js:80:29)\n    at /usr/local/lib/node_modules/npm/node_modules/which/which.js:89:16\n    at /usr/local/lib/node_modules/npm/node_modules/which/node_modules/isexe/index.js:42:5\n    at /usr/local/lib/node_modules/npm/node_modules/which/node_modules/isexe/mode.js:8:5\n    at FSReqWrap.oncomplete (fs.js:170:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python /usr/bin/python
gyp verb check python version `/usr/bin/python -c "import platform; print(platform.python_version());"` returned: "2.7.10\n"
gyp verb get node dir no --target version specified, falling back to host node version: 9.10.1
gyp verb command install [ '9.10.1' ]
gyp verb install input version string "9.10.1"
gyp verb install installing version: 9.10.1
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version not already installed, continuing with install 9.10.1
gyp verb ensuring nodedir is created /Users/ilg/.node-gyp/9.10.1
gyp WARN EACCES user "root" does not have permission to access the dev dir "/Users/ilg/.node-gyp/9.10.1"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/lzma-native/.node-gyp"
gyp verb tmpdir == cwd automatically will remove dev files after to save disk space
gyp verb command install [ '9.10.1' ]
gyp verb install input version string "9.10.1"
gyp verb install installing version: 9.10.1
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version not already installed, continuing with install 9.10.1
gyp verb ensuring nodedir is created /usr/local/lib/node_modules/lzma-native/.node-gyp/9.10.1
gyp WARN EACCES user "root" does not have permission to access the dev dir "/usr/local/lib/node_modules/lzma-native/.node-gyp/9.10.1"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/lzma-native/.node-gyp"
gyp verb tmpdir == cwd automatically will remove dev files after to save disk space
...
gyp verb command install [ '9.10.1' ]
gyp verb install input version string "9.10.1"
gyp verb install installing version: 9.10.1
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version not already installed, continuing with install 9.10.1
gyp verb ensuring nodedir is created /usr/local/lib/node_modules/lzma-native/.node-gyp/9.10.1
gyp WARN EACCES user "root" does not have permission to access the dev dir "/usr/local/lib/node_modules/lzma-native/.node-gyp/9.10.1"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/lzma-native/.node-gyp"
gyp verb ^Ctmpdir == cwd automatically will remove dev files after to save disk space
npm verb lifecycle lzma-native@3.0.7~install: unsafe-perm in lifecycle false
npm verb lifecycle lzma-native@3.0.7~install: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/usr/local/lib/node_modules/lzma-native/node_modules/.bin:/usr/local/lib/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
npm verb lifecycle lzma-native@3.0.7~install: CWD: /usr/local/lib/node_modules/lzma-native
```

The problem is not related only to Python, I tried both on Ubuntu and ARCH:

[lzma-native-arch.txt](https://github.com/addaleax/lzma-native/files/1867806/lzma-native-arch.txt)

**Comment by addaleax** [comment]
I am pretty sure this is happening because you’re running with `sudo`, which is not something recommended by `npm` in any case.

I can try to look into this, but as far as I can tell, this happens with **any** native module that uses `node-gyp` (which means, effectively, any native module).

**Comment by ilg-ul** [comment]
> I am pretty sure this is happening because you’re running with sudo

How can you install globally on macOS or GNU/Linux without sudo?

**Comment by addaleax** [comment]
The way that `npm` recommended it for a while, is to change the ownership of `/usr/local` (if that’s where it’s installing packages, which seems the to be the case on your mac) to your non-admin user, if that’s the only one using the system.

You could also take a look at https://docs.npmjs.com/getting-started/fixing-npm-permissions.

**Comment by ilg-ul** [comment]
> change the ownership of /usr/local 

unfortunatelly, for the machines where my tools are intended to run, this is not a solution.

anyway, my tools were perfectly functional before adding a dependency to decompres-tarxz; right now I'm removing this dependency and reverting to bz2.

**Comment by addaleax** [comment]
@ilg-ul Which bz2 library are you using? If it’s a native one, it might be helpful to know what they are doing differently.

**Comment by ilg-ul** [comment]
I'm using the `decompress` module.

But your question helped me realize that bz2 might be as risky as xz, so I'll probably revert to .tgz, which seem to no longer need external native modules.

**Comment by addaleax** [comment]
@ilg-ul Yes, but the problem is also not coming from this module. It’s unfortunate that this doesn’t work – if you want to raise an issue at the `node-gyp` repo about it, feel free to do that.

**Comment by addaleax** [comment]
Idk, I can re-open this issue to keep track of it, but don’t expect any miracles – this is still a spare-time OSS project after all.

**Comment by fivdi** [comment]
The global install may complete successfully if the `--unsafe-perm` option is used.
```
sudo npm install -g lzma-native --unsafe-perm
```
