### ISSUE TITLE
node-pre-gyp.entless.org has an expired certificate

### ISSUE THREAD

**Issue by gillessed** [addaleax/lzma-native#57]
Seeing the same thing as #46.

```
21:36:45 node-pre-gyp http GET https://node-pre-gyp.entless.org/lzma-native/lzma_native-v3.0.1-node-v57-darwin-x64.tar.gz
21:36:45 node-pre-gyp ERR! Tried to download(undefined): https://node-pre-gyp.entless.org/lzma-native/lzma_native-v3.0.1-node-v57-darwin-x64.tar.gz 
21:36:45 node-pre-gyp ERR! Pre-built binaries not found for lzma-native@3.0.1 and node@8.9.1 (node-v57 ABI) (falling back to source compile with node-gyp) 
21:36:45 node-pre-gyp http certificate has expired 
21:36:45 node-pre-gyp ERR! build error 
21:36:45 node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp clean' (Error: spawn node-gyp ENOENT)
21:36:45 node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/jenkins/workspace/Mobile/interstellar-ios-develop/node_modules/node-pre-gyp/lib/util/compile.js:77:29)
21:36:45 node-pre-gyp ERR! stack     at emitOne (events.js:116:13)
21:36:45 node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:211:7)
21:36:45 node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:196:12)
21:36:45 node-pre-gyp ERR! stack     at onErrorNT (internal/child_process.js:372:16)
21:36:45 node-pre-gyp ERR! stack     at _combinedTickCallback (internal/process/next_tick.js:138:11)
21:36:45 node-pre-gyp ERR! stack     at process._tickCallback (internal/process/next_tick.js:180:9)
21:36:45 node-pre-gyp ERR! System Darwin 17.4.0
```

Hitting `https://node-pre-gyp.entless.org/lzma-native/lzma_native-v3.0.1-node-v57-darwin-x64.tar.gz` in a browser also gives an invalid cert error.

**Comment by addaleax** [comment]
Yup. I need to set myself a reminder to redeploy after renewing certs… :/ Anyway, thanks for the ping, already done!
