### ISSUE TITLE
Errror when downloading binary and when trying to compile LZMA on Windows.

### ISSUE THREAD

**Issue by takase1121** [addaleax/lzma-native#70]
```C:\Users\User\Desktop\Node.js Project\bots\kashima\kashima-kancolle\src\SuzuyaQT>npm install lzma-native

> lzma-native@4.0.2 install C:\Users\User\Desktop\Node.js Project\bots\kashima\kashima-kancolle\src\SuzuyaQT\node_modules\lzma-native
> node-pre-gyp install --fallback-to-build && rimraf build

node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp WARN Tried to download(404): https://node-pre-gyp.addaleax.net/lzma-native/lzma_native-v4.0.2-node-v67-win32-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not found for lzma-native@4.0.2 and node@11.0.0 (node-v67 ABI, unknown) (falling back to source compile with node-gyp)
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  build
  Microsoft (R) Library Manager Version 14.00.24210.0
  Copyright (C) Microsoft Corporation.  All rights reserved.

     Creating library C:\Users\User\Desktop\Node.js Project\bots\kashima\kashima-kancolle\src\SuzuyaQT\node_modules\lzm
  a-native\deps\bin_x86-64\lzma.lib and object C:\Users\User\Desktop\Node.js Project\bots\kashima\kashima-kancolle\src\
  SuzuyaQT\node_modules\lzma-native\deps\bin_x86-64\lzma.exp
  deploy
  The syntax of the command is incorrect.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(171,5): error MSB6006: "cmd.exe" exi
ted with code 1. [C:\Users\User\Desktop\Node.js Project\bots\kashima\kashima-kancolle\src\SuzuyaQT\node_modules\lzma-na
tive\build\liblzma.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=C:\\Users\\User\\Desktop\\Node.js Project\\bots\\kashima\\kashima-kancolle\\src\\SuzuyaQT\\node_modules\\lzma-native\\binding-v4.0.2-node-v67-win32-x64\\lzma_native.node" "--module_name=lzma_native" "--module_path=C:\\Users\\User\\Desktop\\Node.js Project\\bots\\kashima\\kashima-kancolle\\src\\SuzuyaQT\\node_modules\\lzma-native\\binding-v4.0.2-node-v67-win32-x64" "--napi_version=3" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v67"
gyp ERR! cwd C:\Users\User\Desktop\Node.js Project\bots\kashima\kashima-kancolle\src\SuzuyaQT\node_modules\lzma-native
gyp ERR! node -v v11.0.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=C:\Users\User\Desktop\Node.js Project\bots\kashima\kashima-kancolle\src\SuzuyaQT\node_modules\lzma-native\binding-v4.0.2-node-v67-win32-x64\lzma_native.node --module_name=lzma_native --module_path=C:\Users\User\Desktop\Node.js Project\bots\kashima\kashima-kancolle\src\SuzuyaQT\node_modules\lzma-native\binding-v4.0.2-node-v67-win32-x64 --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v67' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\User\Desktop\Node.js Project\bots\kashima\kashima-kancolle\src\SuzuyaQT\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:962:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
node-pre-gyp ERR! System Windows_NT 10.0.16299
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\User\\Desktop\\Node.js Project\\bots\\kashima\\kashima-kancolle\\src\\SuzuyaQT\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\User\Desktop\Node.js Project\bots\kashima\kashima-kancolle\src\SuzuyaQT\node_modules\lzma-native
node-pre-gyp ERR! node -v v11.0.0
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=C:\Users\User\Desktop\Node.js Project\bots\kashima\kashima-kancolle\src\SuzuyaQT\node_modules\lzma-native\binding-v4.0.2-node-v67-win32-x64\lzma_native.node --module_name=lzma_native --module_path=C:\Users\User\Desktop\Node.js Project\bots\kashima\kashima-kancolle\src\SuzuyaQT\node_modules\lzma-native\binding-v4.0.2-node-v67-win32-x64 --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v67' (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! lzma-native@4.0.2 install: `node-pre-gyp install --fallback-to-build && rimraf build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the lzma-native@4.0.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\User\AppData\Roaming\npm-cache\_logs\2018-11-03T08_53_56_771Z-debug.log
```

this is what i got when i tried to install it on Windows. Anyone have ideas on what is going on?

**Comment by addaleax** [comment]
@takase1121 Is this still an issue? There should be pre-built binaries for Node 11 now.

**Comment by IanMitchell** [comment]
@takase1121 are you getting this through the ffmpeg binary package? Hoping to have it fixed here: https://github.com/kevva/decompress-tarxz/pull/11

**Comment by towfiqi** [comment]
same here... whats the workaround?

**Comment by FrostyHyperX** [comment]
try roll back the version of npm and node to npm:6.4.1 and node:10.15.0 in my case it worked just fine

**Comment by addaleax** [comment]
The build situation has improved a lot as of `lzma-native@6.0.0`, so these kinds of issues should hopefully be less frequent now.
