### ISSUE TITLE
Electron 3.0 support / building for Windows 10

### ISSUE THREAD

**Issue by joolean** [addaleax/lzma-native#77]
I'm trying to use this library in an Electron 3.0 application that I'm building on Windows 10. Native bindings don't get downloaded by node-pre-gyp (which makes sense because there are no Electron 3.0 binaries in https://node-pre-gyp.addaleax.net/lzma-native/) but I also can't build from source - I get the following error at the console:

```
gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\[...]\src\[...]\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\[...]\\src\\[...]\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=C:\\Users\\[...]\\src\\[...]\\node_modules\\lzma-native\\binding-v4.0.3-electron-v3.0-win32-x64\\lzma_native.node" "--module_name=lzma_native" "--module_path=C:\\Users\\[...]\\src\\[...]\\node_modules\\lzma-native\\binding-v4.0.3-electron-v3.0-win32-x64" "--napi_version=3" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=electron-v3.0"
gyp ERR! cwd C:\Users\[...]\src\[...]\node_modules\lzma-native
gyp ERR! node -v v10.15.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
```

Digging deeper reveals that the solution build is failing with the same log as reported in #70.

This ticket may be a duplicate of that one, but it would be resolved for me with Electron 3.0 binaries for 4.0.3.

**Comment by Eli-Black-Work** [comment]
We just ran into this today, too. Possibly related to https://github.com/addaleax/lzma-native/issues/122 . It looks like updating electron might solve the issue.
