### ISSUE TITLE
lmza-native error

### ISSUE THREAD

**Issue by Alerinos** [addaleax/lzma-native#79]
Install:
```
C:\Launcher\app>npm i lzma-native

> lzma-native@4.0.3 install C:\Launcher\app\node_modules\lzma-native
> node-pre-gyp install --fallback-to-build && rimraf build

node-pre-gyp WARN Using request for node-pre-gyp https download
[lzma-native] Success: "C:\Launcher\app\node_modules\lzma-native\binding-v4.0.3-node-v67-win32-x64\lzma_native.node" is installed via remote
+ lzma-native@4.0.3
updated 1 package and audited 609 packages in 2.858s
found 0 vulnerabilities
```
Console:
```
const lzma = require('lzma-native');

(unknown) Uncaught Error: Cannot find module 'C:\Launcher\app\node_modules\lzma-native\binding-v4.0.3-node-webkit-v0.37.3-win32-x64\lzma_native.node'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:680:15)
    at Function.Module._load (internal/modules/cjs/loader.js:600:25)
    at Module.require (internal/modules/cjs/loader.js:736:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at C:\Launcher\app\node_modules\lzma-native\index.js:13:14
    at Object.<anonymous> (C:\Launcher\app\node_modules\lzma-native\index.js:597:3)
    at Module._compile (internal/modules/cjs/loader.js:830:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:847:10)
    at Module.load (internal/modules/cjs/loader.js:697:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:637:12)
    at Function.Module._load (internal/modules/cjs/loader.js:629:3)
    at Module.require (internal/modules/cjs/loader.js:736:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at self.require (<anonymous>:11:26)
    at self.require (<anonymous>:11:26)
    at <anonymous>:1:14
```

**Comment by addaleax** [comment]
@Alerinos I’m not sure if this is still relevant for you, but for Node.js embedders like node-webkit or electron you’ll need to recompile any native addons you’re using, unfortunately.

**Comment by jniles** [comment]
@addaleax, I've also been running into this.  Would it be possible to use something like [prebuild](https://www.npmjs.com/package/prebuild) to download precompiled Windows 10 binaries on Linux/Docker?

**Comment by addaleax** [comment]
@jniles This project does provide prebuilt binaries. However, that doesn’t affect the fact Electron or similar environments still have special needs when it comes to native addons on Windows (due to the fact that the main `.exe` file has a different name).

**Comment by jniles** [comment]
Ah, that makes sense.  Thanks for clarifying and your help.
