### ISSUE TITLE
unable to install lzma-native because of 404 not found error on arm64.

### ISSUE THREAD

**Issue by The-Dark-Phoenix** [addaleax/lzma-native#94]
so i was trying to compile hyper terminal for linux on arm64 but i am not able to install lzma-native which is one of its dependencies. Whenever i try to install it with `npm install lzma-native -g` it gives me this output :
```
➜  tmp npm install lzma-native -g
/usr/local/bin/lzmajs -> /usr/local/lib/node_modules/lzma-native/bin/lzmajs

> lzma-native@6.0.1 install /usr/local/lib/node_modules/lzma-native
> node-pre-gyp install --fallback-to-build && rimraf build

node-pre-gyp WARN Using needle for node-pre-gyp https download 
node-pre-gyp WARN Tried to download(404): https://node-pre-gyp.addaleax.net/lzma-native/lzma_native-v6.0.1-n-api-linux-arm64.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for lzma-native@6.0.1 and node@14.15.0 (node-v83 ABI, glibc) (falling back to source compile with node-gyp) 
gyp: Call to 'sh liblzma-config.sh "/usr/local/lib/node_modules/lzma-native/build" "/usr/local/lib/node_modules/lzma-native/deps/xz-5.2.3.tar.bz2"' returned exit status 2 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Linux 4.14.117-perf-g3e53970
gyp ERR! command "/usr/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/usr/local/lib/node_modules/lzma-native/binding-v6.0.1-n-api-linux-arm64/lzma_native.node" "--module_name=lzma_native" "--module_path=/usr/local/lib/node_modules/lzma-native/binding-v6.0.1-n-api-linux-arm64" "--napi_version=7" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v83"
gyp ERR! cwd /usr/local/lib/node_modules/lzma-native
gyp ERR! node -v v14.15.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/usr/local/lib/node_modules/lzma-native/binding-v6.0.1-n-api-linux-arm64/lzma_native.node --module_name=lzma_native --module_path=/usr/local/lib/node_modules/lzma-native/binding-v6.0.1-n-api-linux-arm64 --napi_version=7 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/lzma-native/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1048:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
node-pre-gyp ERR! System Linux 4.14.117-perf-g3e53970
node-pre-gyp ERR! command "/usr/bin/node" "/usr/local/lib/node_modules/lzma-native/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/local/lib/node_modules/lzma-native
node-pre-gyp ERR! node -v v14.15.0
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok 
Failed to execute '/usr/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/usr/local/lib/node_modules/lzma-native/binding-v6.0.1-n-api-linux-arm64/lzma_native.node --module_name=lzma_native --module_path=/usr/local/lib/node_modules/lzma-native/binding-v6.0.1-n-api-linux-arm64 --napi_version=7 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! lzma-native@6.0.1 install: `node-pre-gyp install --fallback-to-build && rimraf build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the lzma-native@6.0.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/dark-phoenix/.npm/_logs/2020-11-06T16_41_23_420Z-debug.log
```
Does anyone has any idea why this is hapenning. Have you removed suppourt for arm64 ? pls help me.

**Comment by abhineet-mishra** [comment]
I am also getting similar error on MAC when tried to install `npm install lzma-native -g`.

**Comment by seanaye** [comment]
I am also getting the same issue... are there any updates on this?

**Comment by smartfrigde** [comment]
same issue is there any fix for that?

**Comment by addaleax** [comment]
If you are having issues with this:

1. Use the latest version of this library
2. If you are still having issues, open a new ticket and *please* include OS version (e.g. `uname -a` output) and steps to reproduce
