### ISSUE TITLE
Support for Windows on ARM64

### ISSUE THREAD

**Issue by bdr99** [addaleax/lzma-native#97]
I'm trying to build `lzma-native` on my Surface Pro X which runs Windows 10 on ARM64. I'm getting the following error:
```
C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\IDE\VC\VCTargets\Microsoft.Cpp.InvalidPlatform.Targets(22,7): error MSB8007: The Platf
orm for project 'nothing.vcxproj' is invalid.  Platform='arm64'. You may be seeing this message because you are trying to build a project without a solution
file, and have specified a non-default Platform that doesn't exist for this project. [C:\Users\Brandon\terminus\node_modules\node-addon-api\src\nothing.vcxpr
oj]
C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\IDE\VC\VCTargets\Microsoft.Cpp.InvalidPlatform.Targets(22,7): error MSB8007: The Platf
orm for project 'liblzma.vcxproj' is invalid.  Platform='arm64'. You may be seeing this message because you are trying to build a project without a solution
file, and have specified a non-default Platform that doesn't exist for this project. [C:\Users\Brandon\terminus\node_modules\lzma-native\build\liblzma.vcxpro
j]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Windows_NT 10.0.19042
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=C:\\Users\\Brandon\\terminus\\node_modules\\lzma-native\\binding-v6.0.1-n-api-win32-arm64\\lzma_native.node" "--module_name=lzma_native" "--module_path=C:\\Users\\Brandon\\terminus\\node_modules\\lzma-native\\binding-v6.0.1-n-api-win32-arm64" "--napi_version=7" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v83"
gyp ERR! cwd C:\Users\Brandon\terminus\node_modules\lzma-native
gyp ERR! node -v v14.13.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=C:\Users\Brandon\terminus\node_modules\lzma-native\binding-v6.0.1-n-api-win32-arm64\lzma_native.node --module_name=lzma_native --module_path=C:\Users\Brandon\terminus\node_modules\lzma-native\binding-v6.0.1-n-api-win32-arm64 --napi_version=7 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\Brandon\terminus\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1047:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
node-pre-gyp ERR! System Windows_NT 10.0.19042
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Brandon\\terminus\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\Brandon\terminus\node_modules\lzma-native
node-pre-gyp ERR! node -v v14.13.0
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=C:\Users\Brandon\terminus\node_modules\lzma-native\binding-v6.0.1-n-api-win32-arm64\lzma_native.node --module_name=lzma_native --module_path=C:\Users\Brandon\terminus\node_modules\lzma-native\binding-v6.0.1-n-api-win32-arm64 --napi_version=7 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
```

Can ARM64 support be added so that this will build successfully?

**Comment by addaleax** [comment]
That’s either a problem with node-gyp or gyp itself, not with this project. I’ll close this since there’s nothing to do about it here.
