### ISSUE TITLE
Error building lzma-native on FreeBSD with npm=6.0.1 and node=15.5.0

### ISSUE THREAD

**Issue by sydbarrett74** [addaleax/lzma-native#98]
Env: FreeBSD 12 on x64
NPM: 6.0.1
NodeJS: 15.5.0

Hello,

I'm trying to build trilium, for which lzma-native is a dependency. When I attempt to build lzma-native, I get the following:

> lzma-native@6.0.1 install /usr/home/xxx/trilium/node_modules/lzma-native
> node-pre-gyp install --fallback-to-build && rimraf build

```
node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp WARN Tried to download(404): https://node-pre-gyp.addaleax.net/lzma-native/lzma_native-v6.0.1-n-api-freebsd-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not found for lzma-native@6.0.1 and node@15.5.0 (node-v88 ABI, unknown) (falling back to source compile with node-gyp)
gmake: Entering directory '/usr/home/xxx/trilium/node_modules/lzma-native/build'
  CC(target) Release/obj.target/nothing/../node-addon-api/src/nothing.o
  AR(target) Release/obj.target/../node-addon-api/src/nothing.a
  COPY Release/nothing.a
  ACTION binding_gyp_liblzma_target_build .
make[1]: don't know how to make rw. Stop

make[1]: stopped in /usr/home/xxx/trilium/node_modules/lzma-native/build/liblzma
gmake: *** [liblzma.target.mk:13: .] Error 2
gmake: Leaving directory '/usr/home/xxx/trilium/node_modules/lzma-native/build'
gyp ERR! build error
gyp ERR! stack Error: `gmake` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (node:events:376:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:284:12)
gyp ERR! System FreeBSD 12.2-RELEASE
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/usr/home/xxx/trilium/node_modules/lzma-native/binding-v6.0.1-n-api-freebsd-x64/lzma_native.node" "--module_name=lzma_native" "--module_path=/usr/home/xxx/trilium/node_modules/lzma-native/binding-v6.0.1-n-api-freebsd-x64" "--napi_version=7" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v88"
gyp ERR! cwd /usr/home/xxx/trilium/node_modules/lzma-native
gyp ERR! node -v v15.5.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/usr/home/xxx/trilium/node_modules/lzma-native/binding-v6.0.1-n-api-freebsd-x64/lzma_native.node --module_name=lzma_native --module_path=/usr/home/xxx/trilium/node_modules/lzma-native/binding-v6.0.1-n-api-freebsd-x64 --napi_version=7 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v88' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/home/xxx/trilium/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:376:20)
node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1063:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:295:5)
node-pre-gyp ERR! System FreeBSD 12.2-RELEASE
node-pre-gyp ERR! command "/usr/local/bin/node" "/usr/home/xxx/trilium/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/home/xxx/trilium/node_modules/lzma-native
node-pre-gyp ERR! node -v v15.5.0
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/usr/home/xxx/trilium/node_modules/lzma-native/binding-v6.0.1-n-api-freebsd-x64/lzma_native.node --module_name=lzma_native --module_path=/usr/home/xxx/trilium/node_modules/lzma-native/binding-v6.0.1-n-api-freebsd-x64 --napi_version=7 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v88' (1)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: electron-installer-debian@2.0.1 (node_modules/electron-installer-debian):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for electron-installer-debian@2.0.1: wanted {"os":"darwin,linux","arch":"any"} (current: {"os":"freebsd","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! lzma-native@6.0.1 install: `node-pre-gyp install --fallback-to-build && rimraf build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the lzma-native@6.0.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```

Thanks in advance.

**Comment by genneko** [comment]
Hi,
I have exactly the same problem on my FreeBSD installation (FreeBSD 12.2/amd64, node 12.20.1, npm 6.14.8) when I try to build [Joplin app](https://github.com/laurent22/joplin).

As I know very little about node and its build systems / package managers, I'm not sure what can cause this issue, but I could somehow workaround this by creating a symlink 'make' which points to 'gmake', then modifying PATH so that the symlink is found first in the PATH.
```
mkdir ~/bin
ln -s /usr/local/bin/gmake ~/bin/make
PATH=~/bin:$PATH npm install
```

I've also noticed the following line in the build error message and wondered. What is 'rw'?
```
make[1]: don't know how to make rw. Stop
```
Then I added ``printenv`` to ``./liblzma-build.sh`` script and found the following environment variable was set, though I have no idea where this 'rw' came from.
```
MAKEFLAGS=rw -- BUILDTYPE=Release
```

I hope this will be of some help. Thank you.

**Comment by sydbarrett74** [comment]
@genneko Thank you for this advice. I can confirm that I was able to build Trilium by following your instructions.

To the maintainers: Should I close this ticket with a 'work-around found' type of tag? I'm sure that the root cause is the fact that gmake is a second-class citizen on *BSD distributions.

**Comment by sydbarrett74** [comment]
@genneko provides a work-around here: https://github.com/addaleax/lzma-native/issues/98#issuecomment-768871316

This mitigation solves the problem, therefore, no need to keep the ticket open. The problem of gmake being second-class on the various *BSD's is not within the scope of this project to solve.
