### ISSUE TITLE
Error: unable to get local issuer certificate

### ISSUE THREAD

**Issue by renkei** [addaleax/lzma-native#99]
Building of lzma-native with node-gyp fails due to certificate error on Arch Linux.
Anything I can do?

```shell
node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp WARN Pre-built binaries not installable for lzma-native@6.0.1 and node@14.15.4 (node-v83 ABI, glibc) (falling back to source compile with node-gyp)
node-pre-gyp WARN Hit error unable to get local issuer certificate 
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: unable to get local issuer certificate
gyp ERR! stack     at TLSSocket.onConnectSecure (_tls_wrap.js:1497:34)
gyp ERR! stack     at TLSSocket.emit (events.js:315:20)
gyp ERR! stack     at TLSSocket._finishInit (_tls_wrap.js:932:8)
gyp ERR! stack     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:706:12)
gyp ERR! System Linux 5.10.10-arch1-1
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/home/renkei/Development/MyApp/node_modules/lzma-native/binding-v6.0.1-n-api-linux-x64/lzma_native.node" "--module_name=lzma_native" "--module_path=/home/renkei/Development/MyApp/node_modules/lzma-native/binding-v6.0.1-n-api-linux-x64" "--napi_version=7" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v83"
gyp ERR! cwd /home/renkei/Development/MyApp/node_modules/lzma-native
gyp ERR! node -v v14.15.4
gyp ERR! node-gyp -v v7.1.2
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/renkei/Development/MyApp/node_modules/lzma-native/binding-v6.0.1-n-api-linux-x64/lzma_native.node --module_name=lzma_native --module_path=/home/renkei/Development/MyApp/node_modules/lzma-native/binding-v6.0.1-n-api-linux-x64 --napi_version=7 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/renkei/Development/MyApp/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1048:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
node-pre-gyp ERR! System Linux 5.10.10-arch1-1
node-pre-gyp ERR! command "/usr/bin/node" "/home/renkei/Development/MyApp/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/renkei/Development/MyApp/node_modules/lzma-native
node-pre-gyp ERR! node -v v14.15.4
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok 
Failed to execute '/usr/bin/node /usr/lib/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/renkei/Development/MyApp/node_modules/lzma-native/binding-v6.0.1-n-api-linux-x64/lzma_native.node --module_name=lzma_native --module_path=/home/renkei/Development/MyApp/node_modules/lzma-native/binding-v6.0.1-n-api-linux-x64 --napi_version=7 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! lzma-native@6.0.1 install: `node-pre-gyp install --fallback-to-build && rimraf build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the lzma-native@6.0.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/renkei/.npm/_logs/2021-01-25T22_57_25_573Z-debug.log
```

**Comment by renkei** [comment]
Solved, this was a npm configuration issue due to our nexus npm repository manager with self-signed certificates. After fixing the configuration everything works as expected.
